# -*- coding: utf-8 -*-
"""Day8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgTdoLfAHH0clfAu90P2-zqDculCOHAg
"""


contacts = {}


def show_menu():
  print("\n--- İletişim Defteri Menüsü ---")
  print("1. Kişi Ekle")
  print("2. Kişileri Görüntüle")
  print("3. Kişi Ara")
  print("4. Kişi Düzenle")
  print("5. Kişi Sil")
  print("6. Çıkış")


def add_contact():
  name = input("Kişi adını girin: ")
  phone = input("Kişi numarasını girin: ")
  email = input("Kişi e-postasını girin: ")
  # Kişi adı anahtar, telefon ve e-posta detayları ise değer olarak saklanır.
  contacts[name] = {"phone": phone, "email": email}
  print(f"'{name}' kişisi iletişim defterinize başarıyla eklendi!")


def view_contacts():
  if contacts: # Eğer 'contacts' sözlüğü boş değilse (içinde eleman varsa)
    print("\n--- Kişi Listesi ---")
    # Her bir kişi (ad ve detayları) için döngüye girer.
    for name, details in contacts.items():
      print(f"Ad: {name}")
      print(f"Telefon: {details['phone']}")
      print(f"E-posta: {details['email']}")
      print("--------------------") # Kişiler arasını ayırmak için
  else:
    print("İletişim defteriniz boş.")


def search_contact():
  name = input("Aramak istediğiniz kişinin adını girin: ")
  if name in contacts: # Eğer 'name' anahtarı 'contacts' içinde varsa
    print(f"\n--- '{name}' Kişi Detayları ---")
    print(f"Ad: {name}")
    print(f"Telefon: {contacts[name]['phone']}")
    print(f"E-posta: {contacts[name]['email']}")
  else:
    print(f"'{name}' kişisi iletişim defterinizde bulunamadı.")


def edit_contact():
  name = input("Düzenlemek istediğiniz kişinin adını girin: ")
  if name in contacts:
    phone = input("Yeni telefon numarasını girin: ")
    email = input("Yeni e-posta adresini girin: ")
    contacts[name] = {"phone": phone, "email": email} # Kişi bilgileri güncellenir
    print(f"'{name}' kişisi başarıyla güncellendi!")
  else:
    print(f"'{name}' kişisi iletişim defterinizde bulunamadı.")


def delete_contact():
  name = input("Silmek istediğiniz kişinin adını girin: ")
  if name in contacts:
    del contacts[name] # 'del' komutu ile sözlükten öğe silinir.
    print(f"'{name}' kişisi başarıyla silindi!")
  else:
    print(f"'{name}' kişisi iletişim defterinizde bulunamadı.")


  show_menu() # Menüyü gösterir
  choice = input("Seçiminizi girin (1-6): ") # Kullanıcıdan seçim alır

  if choice == "1": # Eğer seçim "1" ise (Kişi Ekle)
    add_contact()
  elif choice == "2": # Eğer seçim "2" ise (Kişileri Görüntüle)
    view_contacts()
  elif choice == "3": # Eğer seçim "3" ise (Kişi Ara)
    search_contact()
  elif choice == "4": # Eğer seçim "4" ise (Kişi Düzenle)
    edit_contact()
  elif choice == "5": # Eğer seçim "5" ise (Kişi Sil)
    delete_contact()
  elif choice == "6": # Eğer seçim "6" ise (Çıkış)
    print("İletişim Defteri'ni kullandığınız için teşekkürler. Güle güle!")
    break # Döngüyü kırar ve programı sonlandırır.
  else: # Geçersiz bir seçim yapıldığında
    print("Geçersiz seçim. Lütfen geçerli bir seçenek (1-6) belirleyin.")
