# -*- coding: utf-8 -*-
"""Day14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdNhufhnaWqe23R82WXu2mGygQigHoqw
"""

import random
import string


def sifre_olustur(length=12):
    if length < 4:
        raise ValueError("Şifre uzunluğu 4'den fazla olmalıdır.")

    buyuk_harfler = string.ascii_uppercase
    kucuk_harfler = string.ascii_lowercase
    rakamlar= string.digits 
    ozel_karakterler = "!@#$%^&*()_+-=[]{}|;:',.<>?/"

    sifre = [
         random.choice(buyuk_harfler),
         random.choice(kucuk_harfler),
         random.choice(rakamlar),
         random.choice(ozel_karakterler)
    
             ]

    tum_karakterler = buyuk_harfler + kucuk_harfler + rakamlar + ozel_karakterler

    sifre += random.choices(tum_karakterler, k=length - 4)
 
    random.shuffle(sifre)

    return ''.join(sifre)

try:
  uzunluk = int(input("İstenen şifre uzunluğunu girin (minimum 4): "))
  sifre = sifre_olustur(uzunluk)
  print("Oluşturulan Şifre:", sifre)
except ValueError as e:
  print(e)
  
  
