# -*- coding: utf-8 -*-
"""Day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PIjf1bR3-DnGdQggvhJds_y0c3-8LGdM
"""

sayi = 4

if sayi > 5:
  print("Sayı 5'ten büyük.")
elif sayi == 5:
  print("Sayı 5'e eşit.")
elif sayi == 4:
  print("Sayı 4'e eşit.")
else:
  print("Sayı 5'ten küçük.")

a = 2
b = 20

if a > 5 or b < 15:
  print("İkisinden biri doğru.")
else:
  print("Her iki koşul da yanlış.")


sayi1 = float(input("İlk sayıyı girin: "))
sayi2 = float(input("İkinci sayıyı girin: "))


print("\n--- Karşılaştırma Sonuçları ----")

if sayi1 == sayi2:
    print(f"Her iki sayı da eşit: {sayi1}")
elif sayi1 > sayi2:
    print(f"{sayi1} sayısı {sayi2} sayısından büyük.")
else:
    print(f"{sayi2} sayısı {sayi1} sayısından büyük.")

if sayi1 == 0 or sayi2 == 0:
    print("\nEn az bir sayı sıfır.")
else:
    print("\nHer iki sayı da sıfır değil.")