# -*- coding: utf-8 -*-
"""Day7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TPB2UzPad2QwAgJzDIeCIOdSbELIXwoE
"""


# Shopping List App

shopping_list = []  

def show_menu():  
 
    print("\n--- Alışveriş Listesi Menüsü ---")  
    print("1. Alışveriş Listesini görüntüle")
    print("2. Öğe ekle")
    print("3. Öğe kaldır")
    print("4. Listeyi Temizle")
    print("5. Çıkış")



while True:
    show_menu()  
    choice = input("Seçiminizi girin (1-5): ")  

    if choice == "1":
        print("\n--- Alışveriş Listesi ---")
        if not shopping_list:  
            print("Alışveriş listeniz şuan boş.")
        else:
            for index, item in enumerate(shopping_list):
                print(f"{index + 1}. {item}")

    elif choice == "2":  
       
        item = input("Listeye ekleyeceğiniz ürünün ismini girin: ")
        shopping_list.append(item)
        print(f"{item} başarıyla eklendi.")

    elif choice == "3":  
     
        item = input("Silmek istediğiniz öğeyi girin: ")
        if item in shopping_list:
            shopping_list.remove(item)
            print(f"{item} başarıyla silindi.")
        else:
           
            print(f"{item} böyle bir ürün listenizde bulunmamaktadır.")

    elif choice == "4":
        shopping_list.clear()
        print("Alışveriş Listeniz başarılı bir şekilde temizlenmiştir.")

    elif choice == "5":
        print("Güle güle! İyi alışverişler.")  
        break  

    else:  
        print("Geçersiz seçim. Lütfen 1 ile 5 arasında bir sayı girin.")
