# -*- coding: utf-8 -*-
"""Day20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EtqfXIx3TkQHyu7eRdMfZX3phCD1jIoF
"""

# ------------ DAY 20 PROJECT : ETKİNLİK GERİ SAYIMI --------------
from datetime import datetime, timedelta
import time

def etkinlik_vaktini_al():
  try:
    date_input = input("Etkinlik tarihini girin (YYYY-AA-GG SS:DD:SS): ")
    return datetime.strptime(date_input, "%Y-%m-%d %H:%M:%S")
  except ValueError:
    print("Geçersiz tarih formatı. Lütfen YYYY-AA-GG SS:DD:SS formatını kullanın.")
    return None

def kalan_vakti_hesapla(etkinlikvakti):
  suanzaman = datetime.now()
  zaman_farki = etkinlikvakti - suanzaman
  return zaman_farki

def geri_sayimi_goster(kalan_sure):
  gunler = kalan_sure.days
  saatler, kalan = divmod(kalan_sure.seconds, 3600)
  dakikalar, saniyeler = divmod(kalan, 60)
  
  print(f"\rKalan Süre: {gunler} gün, {saatler} saat, {dakikalar} dakika, {saniyeler} saniye   ", end="")

def gerisayim_baslangici(etkinlikvakti):
  print(f"Geri sayım başlatılıyor. Etkinlik şu tarihe ayarlandı: {etkinlikvakti}")
  while True:
    kalan_sure = kalan_vakti_hesapla(etkinlikvakti)
    
    if kalan_sure.total_seconds() <= 0:
      print("\n\nGeri Sayım Tamamlandı! Etkinlik zamanı geldi!")
      break
    
    geri_sayimi_goster(kalan_sure)
    time.sleep(1)

if __name__ == "__main__":
  etkinlikvakti = etkinlik_vaktini_al()
  
  if etkinlikvakti:
    gerisayim_baslangici(etkinlikvakti)
  else:
    print("Geri sayım başlatılamadı. Lütfen geçerli bir tarih girin.")
