# -*- coding: utf-8 -*-
"""Day9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yA12SeDiyYXc6E6vDFHvS7BcMW3FiSV7
"""



# Malzeme Kontrolcüsü

# Tarif malzemelerini tanımla
tarif_malzemeleri = {"un", "şeker", "tereyağı", "yumurta", "süt"}

# Kullanıcıdan mevcut malzemeleri al
kullanici_girisi = input("Sahip olduğunuz malzemeleri girin (virgülle ayırarak): ")
kullanici_malzemeleri = set(kullanici_girisi.split(", "))

# Malzemeleri karşılaştır
eksik_malzemeler = tarif_malzemeleri - kullanici_malzemeleri
fazla_malzemeler = kullanici_malzemeleri - tarif_malzemeleri

# Sonuçları göster
print("\n--- Malzeme Kontrol Sonuçları ----")
if eksik_malzemeler:
    print(f"Aşağıdaki malzemeler eksik: {', '.join(eksik_malzemeler)}")
else:
    print("Gerekli tüm malzemelere sahipsiniz.")

if fazla_malzemeler:
    print(f"Fazladan malzemeleriniz var: {', '.join(fazla_malzemeler)}")
else:
    print("Gerekli tüm malzemelere sahipsiniz.")
